version: 2.1

orbs:
  slack: circleci/slack@4.13.2

base_container: &base_container
  image: buildpack-deps:bookworm

build_containers: &build_containers
  resource_class: medium
  docker:
    - <<: *base_container

slack_context: &slack_context
  context:
    - slack

only_main: &only_main
  filters:
    branches:
      only:
        - main

only_dependabot: &only_dependabot
  filters:
    branches:
      only:
        - /^dependabot.*/

only_main_and_dependabot: &only_main_and_dependabot
  filters:
    branches:
      only:
        - main
        - /^dependabot.*/

commands:
  notify:
    steps:
      - when:
          condition:
            matches:
              pattern: "^dependabot.*"
              value: << pipeline.git.branch >>
          steps:
            - slack/notify:
                event: fail
                channel: builds-dependabot
                template: SLACK_FAILURE_NOTIFICATION
            - slack/notify:
                event: pass
                channel: builds-dependabot
                template: SLACK_SUCCESS_NOTIFICATION
      - when:
          condition:
            matches:
              pattern: "^(?!dependabot).*"
              value: << pipeline.git.branch >>
          steps:
            - slack/notify:
                event: fail
                channel: dev
                template: SLACK_FAILURE_NOTIFICATION
            - slack/notify:
                event: pass
                channel: builds
                template: SLACK_SUCCESS_NOTIFICATION

  configure_build_tools:
    steps:
      - run: ./scripts/ci/common/install-slack-deps.sh
      - restore_cache:
          keys:
            - asdf-dependencies-{{ arch }}-v2-{{ checksum ".tool-versions" }}
            - asdf-dependencies-{{ arch }}-v2-
      - run: ./scripts/ci/common/install-asdf.sh
      - run: ./scripts/ci/common/configure-asdf.sh
      - run: ./scripts/ci/common/install-asdf-dependencies.sh
      - save_cache:
          key: asdf-dependencies-{{ arch }}-v2-{{ checksum ".tool-versions" }}
          paths:
            - ~/.asdf

  configure_leiningen:
    steps:
      - restore_cache:
          keys:
            - leiningen-v1-{{ checksum "Rakefile" }}
            - leiningen-v1-
      - run: ./scripts/ci/common/ensure-leiningen.sh
      - save_cache:
          key: leiningen-v1-{{ checksum "Rakefile" }}
          paths:
            - vendor/leiningen
            - ~/.lein

  configure_vendored_tools:
    steps:
      - configure_leiningen

  configure_secrets_tools:
    steps:
      - run: ./scripts/ci/common/upgrade-gpg.sh
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh

  configure_release_tools:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:c+72W8vBuVauCyFe/gJVzLOhhX6W9Tg4CJtMoI4CEUg"
      - run: ./scripts/ci/common/configure-git.sh
      - run: ./scripts/ci/common/configure-clojars.sh

jobs:
  build:
    <<: *build_containers
    steps:
      - checkout
      - restore_dependency_caches
      - configure_secrets_tools
      - configure_build_tools
      - configure_vendored_tools
      - run: ./scripts/ci/steps/build.sh
      - save_dependency_caches
      - notify

  prerelease:
    <<: *build_containers
    steps:
      - checkout
      - restore_dependency_caches
      - configure_secrets_tools
      - configure_build_tools
      - configure_vendored_tools
      - configure_secrets_tools
      - configure_release_tools
      - run: ./scripts/ci/steps/prerelease.sh
      - notify

  release:
    <<: *build_containers
    steps:
      - checkout
      - restore_dependency_caches
      - configure_secrets_tools
      - configure_build_tools
      - configure_vendored_tools
      - configure_secrets_tools
      - configure_release_tools
      - run: ./scripts/ci/steps/release.sh
      - notify

  merge_pull_request:
    <<: *build_containers
    steps:
      - checkout
      - configure_secrets_tools
      - configure_build_tools
      - run: ./scripts/ci/steps/merge-pull-request.sh
      - notify

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          <<: *only_main_and_dependabot
          <<: *slack_context
      - merge_pull_request:
          <<: *only_dependabot
          <<: *slack_context
          requires:
            - build
      - prerelease:
          <<: *only_main
          <<: *slack_context
          requires:
            - build
      - slack/on-hold:
          <<: *only_main
          <<: *slack_context
          requires:
            - prerelease
          channel: release
          template: SLACK_ON_HOLD_NOTIFICATION
      - hold:
          <<: *only_main
          type: approval
          requires:
            - prerelease
            - slack/on-hold
      - release:
          <<: *only_main
          <<: *slack_context
          requires:
            - hold
